name: SonarCloud Analysis

on:
  push:
    branches:
      - development
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - development
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configurar Maven Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Rodar análise do SonarCloud
        run: mvn clean verify sonar:sonar -Dsonar.branch.name=development
        env:
            SONAR_HOST_URL: "https://sonarcloud.io"
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
            SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      - name: Exibir logs de erro dos testes
        if: failure()
        run: cat target/surefire-reports/*.txt || true
